### ISSUE TITLE
Pull over patch from 747.sampleflow

### ISSUE THREAD

**Issue by bangerth** [kronbichler/spec-femflow#3]
You'll need this commit too: https://github.com/bangerth/spec-cpuv8-sampleflow/commit/4a220f3e1002bf1394ce43b0afc96fb8dbb639f9

**Comment by bangerth** [comment]
And this one: https://github.com/bangerth/spec-cpuv8-sampleflow/commit/7eff6edf698d4d106d29a7c567654a444eb5c7c9

**Comment by kronbichler** [comment]
Fixed by 379fb88ec5b11f183cd0abe33eede8cc2e40136e and 53b93f09c060b5e85dbc3e4fdb665fa21bd3420e. Thank you!
